.MODEL SMALL
.DATA
;BACKGROUND
BACKGROUNDIMAGE         DB      ?
SCREENWIDTH             EQU     320
SCREENHEIGHT            EQU     200
SCREENSIZE              EQU     SCREENHEIGHT*SCREENWIDTH
;RANDOMIZATION
LINELENGTH              EQU     50
LINEWIDTH               EQU     20
STARTX                  EQU     0
STARTY                  EQU     (SCREENHEIGHT-LINEWIDTH)/2
NUMBEROFLINES           EQU     7
.CODE
MAIN PROC FAR
MOV AX, @DATA
MOV DS, AX

MOV AH,0
MOV AL,13H
INT 10H

MOV AX, 0A000H
MOV ES, AX
MOV DI, 0

;BACKGROUND WITH IMAGE
BACKGROUND:
MOV CX, SCREENSIZE
BACKGROUNDLOOP:
    MOV AL, 63H
    MOV ES:[DI], AL
    INC DI
LOOP BACKGROUNDLOOP

;RESET
MOV DI, STARTY*SCREENWIDTH
ADD DI, STARTX

;TRACK
;FIRST LINE RIGHT
MOV CX, LINELENGTH
MOV AL, 0H
LINELOOP:
    PUSH CX
    PUSH DI
    MOV CX, LINEWIDTH
    LINEWIDTHLOOP:
    
    MOV ES:[DI], AL
    ADD DI, SCREENWIDTH
    LOOP LINEWIDTHLOOP
    POP DI
    POP CX
    INC DI
LOOP LINELOOP

MAIN ENDP
END MAIN


